In [6]:
file = open("sample_file")
contents = file.read()
print(contents)

Hello World
My name is Deepak
I work at Salesforce as a Senior Analyst

In [12]:
with open("sample_file") as f:
    file_content = f.read()
    print(file_content)

Hello World
My name is Deepak
I work at Salesforce as a Senior Analyst

In [16]:
with open("sample_file",'a') as f:
    f.write("\nI love Python")
    f.close()

In [1]:
import pandas as pd

data = pd.read_csv("./Day-24-Mail-Merge/weather.csv")
print(data.head())

         day  temp condition
0     Monday    24     Sunny
1    Tuesday    26     Rainy
2  Wednesday    28    Cloudy
3   Thursday    30     Sunny
4     Friday    22     Dusky

In [18]:
data_dict = data.to_dict()
print(data_dict)

{'day': {0: 'Monday', 1: 'Tuesday', 2: 'Wednesday', 3: 'Thursday', 4: 'Friday', 5: 'Saturday', 6: 'Sunday'}, 'temp': {0: 24, 1: 26, 2: 28, 3: 30, 4: 22, 5: 24, 6: 26}, 'condition': {0: 'Sunny', 1: 'Rainy', 2: 'Cloudy', 3: 'Sunny', 4: 'Dusky', 5: 'Cloudy', 6: 'Sunny'}}

In [19]:
data_dict2 = data.to_dict('list')
print(data_dict2)

{'day': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'], 'temp': [24, 26, 28, 30, 22, 24, 26], 'condition': ['Sunny', 'Rainy', 'Cloudy', 'Sunny', 'Dusky', 'Cloudy', 'Sunny']}

In [21]:
data_dict3 = data.to_dict('series')
print(data_dict3)

{'day': 0       Monday
1      Tuesday
2    Wednesday
3     Thursday
4       Friday
5     Saturday
6       Sunday
Name: day, dtype: object, 'temp': 0    24
1    26
2    28
3    30
4    22
5    24
6    26
Name: temp, dtype: int64, 'condition': 0     Sunny
1     Rainy
2    Cloudy
3     Sunny
4     Dusky
5    Cloudy
6     Sunny
Name: condition, dtype: object}

In [22]:
data_dict4 = data.to_dict('records')
print(data_dict4)

[{'day': 'Monday', 'temp': 24, 'condition': 'Sunny'}, {'day': 'Tuesday', 'temp': 26, 'condition': 'Rainy'}, {'day': 'Wednesday', 'temp': 28, 'condition': 'Cloudy'}, {'day': 'Thursday', 'temp': 30, 'condition': 'Sunny'}, {'day': 'Friday', 'temp': 22, 'condition': 'Dusky'}, {'day': 'Saturday', 'temp': 24, 'condition': 'Cloudy'}, {'day': 'Sunday', 'temp': 26, 'condition': 'Sunny'}]

In [23]:
data_dict5 = data.to_dict('index')
print(data_dict5)

{0: {'day': 'Monday', 'temp': 24, 'condition': 'Sunny'}, 1: {'day': 'Tuesday', 'temp': 26, 'condition': 'Rainy'}, 2: {'day': 'Wednesday', 'temp': 28, 'condition': 'Cloudy'}, 3: {'day': 'Thursday', 'temp': 30, 'condition': 'Sunny'}, 4: {'day': 'Friday', 'temp': 22, 'condition': 'Dusky'}, 5: {'day': 'Saturday', 'temp': 24, 'condition': 'Cloudy'}, 6: {'day': 'Sunday', 'temp': 26, 'condition': 'Sunny'}}

In [24]:
data_dict6 = data.to_dict('split')
print(data_dict6)

{'index': [0, 1, 2, 3, 4, 5, 6], 'columns': ['day', 'temp', 'condition'], 'data': [['Monday', 24, 'Sunny'], ['Tuesday', 26, 'Rainy'], ['Wednesday', 28, 'Cloudy'], ['Thursday', 30, 'Sunny'], ['Friday', 22, 'Dusky'], ['Saturday', 24, 'Cloudy'], ['Sunday', 26, 'Sunny']]}

In [25]:
data_dict7 = data.to_dict('tight')
print(data_dict7)

{'index': [0, 1, 2, 3, 4, 5, 6], 'columns': ['day', 'temp', 'condition'], 'data': [['Monday', 24, 'Sunny'], ['Tuesday', 26, 'Rainy'], ['Wednesday', 28, 'Cloudy'], ['Thursday', 30, 'Sunny'], ['Friday', 22, 'Dusky'], ['Saturday', 24, 'Cloudy'], ['Sunday', 26, 'Sunny']], 'index_names': [None], 'column_names': [None]}

In [26]:
json = data.to_json()
print(json)

{"day":{"0":"Monday","1":"Tuesday","2":"Wednesday","3":"Thursday","4":"Friday","5":"Saturday","6":"Sunday"},"temp":{"0":24,"1":26,"2":28,"3":30,"4":22,"5":24,"6":26},"condition":{"0":"Sunny","1":"Rainy","2":"Cloudy","3":"Sunny","4":"Dusky","5":"Cloudy","6":"Sunny"}}

In [36]:
json2 = data.to_json(orient='records')
print(json2)

[{"day":"Monday","temp":24,"condition":"Sunny"},{"day":"Tuesday","temp":26,"condition":"Rainy"},{"day":"Wednesday","temp":28,"condition":"Cloudy"},{"day":"Thursday","temp":30,"condition":"Sunny"},{"day":"Friday","temp":22,"condition":"Dusky"},{"day":"Saturday","temp":24,"condition":"Cloudy"},{"day":"Sunday","temp":26,"condition":"Sunny"}]

In [37]:
mean_temp = data["temp"].mean()
print(mean_temp)

25.714285714285715

In [2]:
data['day']

0       Monday
1      Tuesday
2    Wednesday
3     Thursday
4       Friday
5     Saturday
6       Sunday
Name: day, dtype: object

In [3]:
data.day

0       Monday
1      Tuesday
2    Wednesday
3     Thursday
4       Friday
5     Saturday
6       Sunday
Name: day, dtype: object

In [4]:
data[data.day =='Monday']

      day  temp condition
0  Monday    24     Sunny

In [6]:
data[data.temp >= 25]

         day  temp condition
1    Tuesday    26     Rainy
2  Wednesday    28    Cloudy
3   Thursday    30     Sunny
6     Sunday    26     Sunny

In [7]:
data[data.temp == data.temp.max()]

        day  temp condition
3  Thursday    30     Sunny

In [8]:
Monday = data[data.day =='Monday']
Monday.condition

0    Sunny
Name: condition, dtype: object

In [10]:
data_dictionary = {"students": ['Ana','James','Mary'],
                   "score": [98,90,67]}

new_data_frame = pd.DataFrame(data_dictionary)
print(new_data_frame)

  students  score
0      Ana     98
1    James     90
2     Mary     67

# List Comprehension

In [12]:
a = [1,2,3,4,5]
print(a)

b = [i**2 for i in a]
print(b)

[1, 2, 3, 4, 5]
[1, 4, 9, 16, 25]

In [15]:
word = 'Batman'
letters = [letter for letter in word]
print(letters)

['B', 'a', 't', 'm', 'a', 'n']

In [16]:
# Conditional list comprehension

names = ['Ben','Beth','Carl','Denise','Mark','Hilton','James']
print(names)

short_names = [name for name in names if len(name) <= 4]
print(short_names)

['Ben', 'Beth', 'Carl', 'Denise', 'Mark', 'Hilton', 'James']
['Ben', 'Beth', 'Carl', 'Mark']

In [22]:
# Dictionary comprehension
import random
names = ['Ben','Beth','Carl','Denise','Mark','Hilton','James']
print(names)

names_dic = {name:len(name) for name in names}
print(names_dic)

student_scores = {name:random.randint(0,100) for name in names}
print(student_scores)

new_names_dic = {key:key.upper() for (key,value) in names_dic.items()}
print(new_names_dic)

passed_students = {name:score for (name,score) in student_scores.items() if score> 60}
print(passed_students)

['Ben', 'Beth', 'Carl', 'Denise', 'Mark', 'Hilton', 'James']
{'Ben': 3, 'Beth': 4, 'Carl': 4, 'Denise': 6, 'Mark': 4, 'Hilton': 6, 'James': 5}
{'Ben': 9, 'Beth': 78, 'Carl': 83, 'Denise': 56, 'Mark': 90, 'Hilton': 24, 'James': 72}
{'Ben': 'BEN', 'Beth': 'BETH', 'Carl': 'CARL', 'Denise': 'DENISE', 'Mark': 'MARK', 'Hilton': 'HILTON', 'James': 'JAMES'}
{'Beth': 78, 'Carl': 83, 'Mark': 90, 'James': 72}

In [24]:
import pandas as pd

sample_df = pd.read_csv("./Day-24-Mail-Merge/weather.csv")
print(sample_df.head())

for (index, row) in sample_df.iterrows():
    print(row)

         day  temp condition
0     Monday    24     Sunny
1    Tuesday    26     Rainy
2  Wednesday    28    Cloudy
3   Thursday    30     Sunny
4     Friday    22     Dusky
day          Monday
temp             24
condition     Sunny
Name: 0, dtype: object
day          Tuesday
temp              26
condition      Rainy
Name: 1, dtype: object
day          Wednesday
temp                28
condition       Cloudy
Name: 2, dtype: object
day          Thursday
temp               30
condition       Sunny
Name: 3, dtype: object
day          Friday
temp             22
condition     Dusky
Name: 4, dtype: object
day          Saturday
temp               24
condition      Cloudy
Name: 5, dtype: object
day          Sunday
temp             26
condition     Sunny
Name: 6, dtype: object